runtime: nodejs24
instance_class: F1

# This section removes the warning and sets your scaling limit
automatic_scaling:
  max_instances: 10
  min_instances: 1

network:
  session_affinity: true
