runtime: nodejs
env: flex

# This tells Google to use a modern, supported OS and Node version
runtime_config:
  operating_system: "ubuntu22"
  runtime_version: "22"

# Keeps costs as low as possible by strictly running 1 instance
manual_scaling:
  instances: 1

network:
  session_affinity: true
